export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_RETRIEVING = 'AUTH_RETRIEVING';
export const AUTH_RETRIEVED = 'AUTH_RETRIEVED';

export const TESTS_FETCH_ALL = 'TESTS_FETCH_ALL';
export const TESTS_FETCH_ONE = 'TESTS_FETCH_ONE';
export const TESTS_LOADING = 'TESTS_LOADING';
export const TESTS_LOADED = 'TESTS_LOADED';

export const DOMAINS_FETCH_ALL = 'DOMAINS_FETCH_ALL';
export const DOMAINS_FETCH_ONE = 'DOMAINS_FETCH_ONE';
export const DOMAINS_LOADING = 'DOMAINS_LOADING';
export const DOMAINS_LOADED = 'DOMAINS_LOADED';

export const QUESTIONS_FETCH_ALL = 'QUESTIONS_FETCH_ALL';
export const QUESTIONS_FETCH_ONE = 'QUESTIONS_FETCH_ONE';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const QUESTIONS_LOADED = 'QUESTIONS_LOADED';
