export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_RETRIEVING = 'AUTH_RETRIEVING';
export const AUTH_RETRIEVED = 'AUTH_RETRIEVED';

export const TESTS_FETCH_ALL = 'TESTS_FETCH_ALL';
export const TESTS_LOADING = 'TESTS_LOADING';
export const TESTS_LOADED = 'TESTS_LOADED';
